### ISSUE TITLE
Locale & OS dependent failures

### ISSUE THREAD

**Issue by Grinnz** [Grinnz/Dir-ls#4]
Migrated from [rt.cpan.org #122379](https://rt.cpan.org/Ticket/Display.html?id=122379) (status was 'new')

Requestors:
* SREZIC@cpan.org (@eserte)

From srezic@cpan.org (@eserte) on 2017-07-06 17:25:40:

On some of my smokers I see test failures like this:

```
...
#   Failed test 'default list correct'
#   at t/ls.t line 23.
#     Structures begin differing at:
#          $got->[0] = 'TEST3'
#     $expected->[0] = 'test1'

#   Failed test 'reverse list correct'
#   at t/ls.t line 28.
#     Structures begin differing at:
#          $got->[3] = 'test5'
#     $expected->[3] = 'Test_6.Txt'
... (etc) ...
```

It seems that the failures happen for specific locales (C or POSIX) on Linux systems. On FreeBSD systems I did not manage to get any pass reports, neither with C locale nor en_US.UTF-8.

**Comment by Grinnz** [comment]
@eserte is this still a problem with the latest version?

**Comment by eserte** [comment]
The matrix looks green, so probably it's resolved: http://matrix.cpantesters.org/?dist=Dir-ls+0.004
